; ============================================================================
; ENVIRONNEMENT 1 : ESP32 Physique (Cible Matérielle)
; ============================================================================
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
