; ============================================================================
; ENVIRONNEMENT 1 : ESP32 Physique (Cible Matérielle)
; ============================================================================
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
"""
; ============================================================================
; ENVIRONNEMENT 2 : Simulation PC Native (Sans Matériel)
; ============================================================================
[env:native]
platform = native
build_flags = 
    -D USE_MOCK_SENSORS=1
    -D USE_MOCK_STORAGE=1
    -I include               ; Permet de trouver Arduino.h et config.h sur PC
    -std=c++11               ; Norme C++ standard pour le compilateur de ton PC
    """